[package]
name = "ssbu-combat-latency-slider"
version = "1.0.0"
authors = ["Atamol"]
edition = "2018"
license = "AGPL-3.0-only"

[package.metadata.skyline]
titleid = "01006A800016E000"

[lib]
crate-type = ["cdylib"]

[dependencies]
ninput = { git = "https://github.com/blu-dev/ninput", version = "0.1.0" }
skyline = { git = "https://github.com/ultimate-research/skyline-rs.git" }
once_cell = { version = "1.20.2", default-features = true }

[features]
# locked-latency builds: pick one of 0f/1f/2f/3f
fixed = []
0f = ["fixed"]
1f = ["fixed"]
2f = ["fixed"]
3f = ["fixed"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
